---
abstract: 'Petal View Class'
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Petal
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.7006
  Petal: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-View-Petal/
version: 0.03
